frameworkVersion: "^4.1.12"

service: hello-retail-product-catalog-api

custom:
  stage: dev
  
  retailStreamVersion: 1
  
  productCatalogBuilderVersion: 1
  
  productCatalogApiVersion: 1
  
  # Exports
  exportProductCatalogRestApi: hello-retail-product-catalog-api:dev:ProductCatalogRestApi:1

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: ${env:MEMORY_SIZE}
  region: ap-northeast-2
  stage: dev
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:PutItem
          Resource: !Sub "arn:aws:dynamodb:ap-northeast-2:590183717745:table/${MetricsTablePhotoFail}"

functions:
  categories:
    role:
      Fn::GetAtt: [ ProductCatalogApiCategoriesReader, Arn ]
    handler: catalogApi.categories
    environment:
      TABLE_PRODUCT_CATEGORY_NAME:
        Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCategoryTableName:1
    events:
      - http:
          path: categories
          method: get
          cors: true
  products:
    role:
      Fn::GetAtt: [ ProductCatalogApiProductsReader, Arn ]
    handler: catalogApi.products
    environment:
      TABLE_PRODUCT_CATALOG_NAME:
        Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCatalogTableName:1
    events:
      - http:
          path: products
          method: get
          cors: true

resources:
  Resources:
    MetricsTableProductCatalogApi:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: metrics.product-catalog-api
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Log Group
    CategoriesLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/hello-retail-product-catalog-api-dev-categories
        RetentionInDays: 7
    ProductsLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/hello-retail-product-catalog-api-dev-products
        RetentionInDays: 7
    # Product Catalog Roles
    ProductCatalogApiCategoriesReader: # role for Categories Lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: devProductCatalogApiCategoriesReader1
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    Fn::GetAtt: [ CategoriesLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    Fn::Join:
                      - ':'
                      - - Fn::GetAtt: [ CategoriesLogGroup, Arn ]
                        - '*'
          - PolicyName: ReadFromCategories
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -  Effect: Allow
                   Action:
                     - 'dynamodb:Scan'
                   Resource:
                    Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCategoryTableArn:1
    ProductCatalogApiProductsReader: # role for Products Lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: devProductCatalogApiProductsReader1
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    Fn::GetAtt: [ ProductsLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    Fn::Join:
                      - ':'
                      - - Fn::GetAtt: [ ProductsLogGroup, Arn ]
                        - '*'
          - PolicyName: ReadFromProducts
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -  Effect: Allow
                   Action:
                     - 'dynamodb:GetItem'
                   Resource:
                    Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCatalogTableArn:1
                -  Effect: Allow
                   Action:
                     - 'dynamodb:Query'
                   Resource:
                    Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCatalogTableCategoryIndexArn:1

  Outputs:
    ProductCatalogRestApi:
      Description: API used to access the product and category catalog in DynamoDB
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: hello-retail-product-catalog-api:dev:ProductCatalogRestApi:1
