frameworkVersion: "^4.1.12"

service: hello-retail-product-photos

custom:
  stage: dev
  
  retailStreamVersion: 1
  
provider:
  name: aws
  runtime: nodejs20.x
  region: ap-norhteast-2
  memorySize: ${env:MEMORY_SIZE}
  stage: dev
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:PutItem
          Resource: !Sub "arn:aws:dynamodb:ap-northeast-2:590183717745:table/${MetricsTablePhotoFail}"

functions:
  processor:
    role:
      'Fn::GetAtt': [ ProcessorRole, Arn ]
    handler: processor.processKinesisEvent
    environment:
      STAGE: dev
      STEP_FUNCTION:
        'Fn::ImportValue': hello-retail-product-photos-process:dev:PhotoAssignmentsStepFunctionArn:1
      TABLE_PHOTO_REGISTRATIONS_NAME:
        'Fn::ImportValue': hello-retail-product-photos-data:dev:PhotoRegistrationsTableName:1
    events:
      - stream:
          arn: arn:aws:kinesis:ap-northeast-2:${env:ACCOUNT_ID}:stream/devRetailStream
          enabled: true
          startingPosition: TRIM_HORIZON

resources:
  Resources:
    MetricsTablePhotoProcessor:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: metrics.photo-processor
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Log Group
    ProcessorLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: '/aws/lambda/hello-retail-product-photos-dev-processor'
        RetentionInDays: 7
    # Role
    ProcessorRole: # role for the photo assignment step function execution kick-off lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: devProductPhotosProcessor1
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    'Fn::GetAtt': [ ProcessorLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    'Fn::Join':
                      - ':'
                      - - 'Fn::GetAtt': [ ProcessorLogGroup, Arn ]
                        - '*'
          - PolicyName: ReadFromKinesis
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'kinesis:GetRecords'
                    - 'kinesis:GetShardIterator'
                    - 'kinesis:DescribeStream'
                    - 'kinesis:ListStreams'
                  Resource:
                    Fn::ImportValue: hello-retail-stream:dev:RetailStreamArn:1
          - putPhotoRegistrations:
              PolicyName: PutPhotoRegistrations
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  -  Effect: Allow
                    Action:
                      - 'dynamodb:PutItem'
                    Resource:
                      'Fn::ImportValue': hello-retail-product-photos-data:dev:PhotoRegistrationsTableArn:1
          - updatePhotoRegistrations:
              PolicyName: UpdatePhotoRegistrations
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  -  Effect: Allow
                    Action:
                      - 'dynamodb:UpdateItem'
                    Resource:
                      'Fn::ImportValue': hello-retail-product-photos-data:dev:PhotoRegistrationsTableArn:1
          - PolicyName: ExecuteStepFunction  # see https://forums.aws.amazon.com/thread.jspa?messageID=755476&tstart=0 for StepFunction IAM docs
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'states:StartExecution'
                  Resource:
                    'Fn::ImportValue': hello-retail-product-photos-process:dev:PhotoAssignmentsStepFunctionArn:1
