frameworkVersion: "^4.1.12"

service: hello-retail-product-photos-fail

custom:
  stage: dev

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  memorySize: ${env:MEMORY_SIZE}
  stage: dev
  iam:
    role:
      statements: # permissions for all of your functions can be set here
        - Effect: Allow
          Action: # Gives permission to DynamoDB tables in a specific region
            - dynamodb:PutItem
          Resource: !Sub "arn:aws:dynamodb:ap-northeast-2:590183717745:table/${MetricsTablePhotoFail}"

functions:
  fail:
    role:
      'Fn::GetAtt': [ FailRole, Arn ]
    handler: fail.handler
    environment:
      TABLE_PHOTO_ASSIGNMENTS_NAME:
        Fn::ImportValue: hello-retail-product-photos-data:dev:PhotoAssignmentsTableName:1

resources:
  Resources:
    MetricsTablePhotoFail:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: metrics.photo-fail
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # Log Group
    FailLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: '/aws/lambda/hello-retail-product-photos-fail-dev-fail'
        RetentionInDays: 7
    # Role
    FailRole: # role for the assignment failing lambda
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: devProductPhotosFail1
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: CreateAndWriteToLogStream
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogStream'
                  Resource:
                    'Fn::GetAtt': [ FailLogGroup, Arn ]
                - Effect: Allow
                  Action:
                    - 'logs:PutLogEvents'
                  Resource:
                    'Fn::Join':
                      - ':'
                      - - 'Fn::GetAtt': [ FailLogGroup, Arn ]
                        - '*'
          - ${file(./../productPhotos.yml):deletePhotoAssignment}
  Outputs:
    FailLambdaName:
      Description: The Name of the Photo Assignments Fail Lambda
      Value:
        Ref: FailLambdaFunction
      Export:
        Name: hello-retail-product-photos-fail:dev:PhotoAssignmentsFailLambdaName:1
    FailLambdaArn:
      Description: The Name of the Photo Assignments Fail Lambda
      Value:
        'Fn::GetAtt': [ FailLambdaFunction, Arn ]
      Export:
        Name: hello-retail-product-photos-fail:dev:PhotoAssignmentsFailLambdaArn:1
