frameworkVersion: "^4.1.12"

service: hello-retail-website

plugins:
  - ./.serverless_plugins/web-app-build-plugin.js


custom:
  # AWS ARN for the S3 bucket used to host the site.
  bucketArn:
    Fn::Join: # e.g. arn:aws:s3:::stage.hello-retail.biz/*
      - ''
      - - 'arn:aws:s3:::'
        - Ref: HelloRetailWebBucket
        - '/*'

  # Domain name for CloudFront distribution.
  cloudFrontDomainName:
    Fn::GetAtt:
      - HelloRetailWebDistribution
      - DomainName

  # Hosted Zone ID for all of CloudFormation.
  cloudFrontHostedZoneId: Z2FDTNDATAQYW2

  # Public domain for the site e.g. hello-retail.biz
  domainName: hello-retail.biz

  # Fully Qualified Domain Name for the hosted website.
  dnsHostName: 
    Fn::If: # e.g. hello-retail.biz or stage.hello-retail.biz
      - ProductionStage
      - hello-retail.biz
      - dev.hello-retail.biz

  # FQDN for direct access to S3 bucket website.
  originDomainName: 
    Fn::Join: # e.g. hello-retail.biz.s3.amazonaws.com
      - ''
      - - ${custom.dnsHostName}
        - '.s3.amazonaws.com'

  # Identifier used for the S3 origin in CloudFront.
  originId: 
    Fn::Join: # e.g. S3-hello-retail.biz or S3-dev.hello-retail.biz
      - ''
      - - 's3-'
        - ${custom.dnsHostName}

  # Import secrets.
  retailStreamVersion: 1

  eventWriterApiVersion: 1
  productCatalogBuilderVersion: 1
  productCatalogApiVersion: 1
  s3Bucket:
    Fn::Join: # e.g. s3://stage.hello-retail.biz/
      - ''
      - - 's3://'
        - Ref: HelloRetailWebBucket
        - '/'

  # Stage name for deployment. Use 'prod' to deploy to production.
  stage: dev
  # 
  webAppBuild:
    configPath: ./config.js
    configValues:
      ImageBucket: hello-retail.biz
      WebAppName: Hello Retail
      Stage: dev
      AWSRegion: ap-northeast-2
      SessionName: hello-retail-website-dev
      WebAppRole: arn:aws:iam::${env:ACCOUNT_ID}:role/devHelloRetailWebIdentity
      ProductCatalogTableName:
        Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCatalogTableName:1
      ProductCategoryTableName:
        Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCategoryTableName:1
      EventWriterApi:
        Fn::ImportValue: hello-retail-event-writer-api:dev:EventWriterRestApi:1
      ProductCatalogApi:
        Fn::ImportValue: hello-retail-product-catalog-api:dev:ProductCatalogRestApi:1
    webpackPath: ./webpack.config.js

  # webApp: ${self:} # externally, use `${file(~/web/serverless.yml)}`, replacing the `~` therein with the appropriate relative reference [e.g. '..' or '../..']
  exportWebApplicationIdentityArn: hello-retail-website:dev:WebApplicationIdentityArn
  exportWebApplicationBucketName: hello-retail-website:dev:WebApplicationBucketName

provider:
  name: aws
  region: ap-northeast-2

resources:
  Conditions:
     ProductionStage: 
       Fn::Equals:
         - dev
         - dev

  Resources:

    # TODO: Web App Role to include policy allowing it to assume all necessary roles

    # ===================== IAM ====================

    WebApplicationIdentity:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: devHelloRetailWebIdentity
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambda_FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: ReadFromProductCatalog
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -  Effect: Allow
                   Action:
                     - 'dynamodb:Scan'
                   Resource:
                    Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCategoryTableArn:1
                -  Effect: Allow
                   Action:
                     - 'dynamodb:GetItem'
                     - 'dynamodb:BatchGetItem'
                     - 'dynamodb:Scan'
                   Resource:
                    Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCatalogTableArn:1
                -  Effect: Allow
                   Action:
                     - 'dynamodb:Query'
                     - 'dynamodb:Scan'
                   Resource:
                    Fn::ImportValue: hello-retail-product-catalog-builder:dev:ProductCatalogTableCategoryIndexArn:1

    # ===================== S3 =====================

    HelloRetailWebBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hello-retail.biz
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - HEAD
              AllowedOrigins:
                - "*"

    HelloRetailWebBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: HelloRetailWebBucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:*
              Effect: Allow
              Resource: ${custom.bucketArn}
              Principal: '*'
            - Action:
                - s3:*
              Effect: Allow
              Resource: ${custom.bucketArn}
              Principal:
                AWS:
                  - 'arn:aws:iam::${env:ACCOUNT_ID}:role/devHelloRetailWebIdentity'
      DependsOn:
        - HelloRetailWebBucket

    # ================ CloudFront ==================

    HelloRetailWebDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: ${custom.originId}
              DomainName: hello-retail.biz.s3.amazonaws.com
              S3OriginConfig:
                OriginAccessIdentity: ''
          Enabled: true
          CustomErrorResponses:
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /error.html
          DefaultRootObject: index.html
          #Aliases:
          #- ${self:custom.dnsHostName}
          DefaultCacheBehavior:
            AllowedMethods:
            - GET
            - HEAD
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
            TargetOriginId: ${custom.originId}
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: allow-all
      DependsOn:
        - HelloRetailWebBucket

    # ================= Route 53 ===================

    #HelloRetailWebRecordSetGroup:
    #  Type: AWS::Route53::RecordSetGroup
    #  Properties:
    #    HostedZoneName: ${self:custom.domainName}.
    #    RecordSets:
    #    - Name: ${self:custom.dnsHostName}
    #      Type: A
    #      AliasTarget:
    #        DNSName: ${self:custom.cloudFrontDomainName}
    #        HostedZoneId: ${self:custom.cloudFrontHostedZoneId}
    #    - Name: ${self:custom.dnsHostName}
    #      Type: AAAA
    #      AliasTarget:
    #        DNSName: ${self:custom.cloudFrontDomainName}
    #        HostedZoneId: ${self:custom.cloudFrontHostedZoneId}
    #  DependsOn:
    #    - HelloRetailWebDistribution

  # ================= Outputs ===================

  Outputs:
    WebApplicationIdentityArn:
      Description: The Role ARN for the Web Application identity
      Value:
        Fn::GetAtt: [ WebApplicationIdentity, Arn ]
      Export:
        Name: hello-retail-website:dev:WebApplicationIdentityArn
    WebApplicationBucketName:
      Description: The S3 Bucket ARN used to host Web Application
      Value:
        Ref: HelloRetailWebBucket
      Export:
        Name: hello-retail-website:dev:WebApplicationBucketName
